NPC's follows the player
mapedorr/popochiu pull request #105
Opened 2023-11-09 04:10 UTC by JuannFerrari

This PR is for issue #84

**What**
Adds missing feature related to `follow_player ` var and allows NPC's to follow the player if the value is `true`

**Why**
To let the player set if an NPC will follow him or not

Demo:

https://github.com/mapedorr/popochiu/assets/24940330/7752b38a-8338-4ea8-a95f-5283e2c384cd

2023-11-09 11:12 UTC, mapedorr requested changes
Looks fine, but needs some improvements.

2023-11-10 04:09 UTC, JuannFerrari commented on addons/popochiu/engine/objects/room/popochiu_room.gd
> +		chr.started_walk_to.connect(_follow_player)
great feedback

2023-11-10 04:35 UTC, JuannFerrari commented
A new demo addressing the comments, NPC is not flipping its sprite 🤔 

https://github.com/mapedorr/popochiu/assets/24940330/bf080bce-f35f-4984-b027-aa55d88fdb67

2023-11-10 14:12 UTC, mapedorr approved these changes

2023-11-10 14:12 UTC, merged