refs #71: Toolbar audio settings
mapedorr/popochiu pull request #74
Opened 2023-08-04 04:19 UTC by JuannFerrari

**What**
This PR adds a new audio settings panel with sliders and saves them into a file, if the file exists the saved settings will be loaded.

**Why**
To let the player modify the audio from the game.

**Screenshot**
![image](https://github.com/mapedorr/popochiu/assets/24940330/7a13a352-b247-4e51-ac3e-fd592949815c)

2023-08-04 06:02 UTC, stickgrinder commented
@JuannFerrari I've left a couple very minor comments. Apart from that, this is very good work to me! Thanks! :)

2023-08-09 14:09 UTC, mapedorr requested changes
Apart from these comments, before we proceed with the merge, we'll need to determine the icon for the button on the toolbar. Let me know if you'd like me to take care of that and provide it to you.

2023-08-09 14:09 UTC, mapedorr commented on addons/popochiu/engine/objects/graphic_interface/sound_settings/sound_settings.gd
> +	am.set_bus_volume_db("Effects", value)
Instead of having three methods, we should have only one that changes the volume of the corresponding bus based on the parameter it receives.

2023-08-09 14:09 UTC, mapedorr commented on addons/popochiu/engine/objects/graphic_interface/sound_settings/sound_settings.tscn
> +max_value = 0.0
These should be created during runtime (except for Master) if we decide to leave developers to define their own buses.

2023-08-29 17:21 UTC, mapedorr commented on addons/popochiu/engine/objects/graphic_interface/toolbar/toolbar.tscn
Yes. We could think about this now that I'm working on refactoring/improving the GUI.

2023-09-01 20:12 UTC, mapedorr requested changes
While testing the Audio settings I found a couple of bugs that we need to fix before merging the PR:

- [x] If you create a new audio bus and then run the game, Godot shows an error in the Output. You can still open the Audio settings popup and see the name of the new bus as part of the buses list, but it is not possible to change its volume.
- [x] Supose you have four buses: Master, Music, SFX, and Voices. If you delete the SFX bus, the Voices bus will show/edit the volume of the SFX bus instead of updating its own volume.
- [x] After installing the plugin on an empty project, Godot shows an error when running the game because it cannot open the `default_bus_layout.tres` file.
- [x] Once you create the `default_bus_layout.tres` file and run the project, Godot shows an error saying that the `volume_settings` variable in **audio_manager.gd** doesn't find an entry for `'Master'`.
- [x] If one deletes the `user://audio_settings.save` file, running the game shows the same error as the previous bug.

2023-09-07 11:07 UTC, mapedorr approved these changes
Very well done!

2023-09-07 11:09 UTC, merged